<?php

namespace Database\Seeders;

use App\Models\Esercizio;
use App\Models\GestoTecnico;
use App\Models\Sport;
use App\Models\User;
use Illuminate\Database\Seeder;

/**
 * 60 esercizi ecologici per pallavolo — Constraints-Led Approach / RLD.
 * Organizzati per fondamentale: 10 esercizi ciascuno.
 * Fondamentali: Ricezione/Difesa, Palleggio, Attacco, Battuta, Muro, Gioco di squadra.
 *
 * Adattato allo schema del progetto:
 *   - tabella: esercizi (nome, descrizione, categoria_eta, gesto_tecnico_id)
 *   - tag ontologici: exercise_category, paradigm_primary, constraint_type,
 *                     representativeness, feedback_suggestion, affordance_targets
 */
class ExerciseEcologicalSeeder extends Seeder
{
    public function run(): void
    {
        $sport      = Sport::where('slug', 'pallavolo')->first();
        $allenatore = User::where('email', 'allenatore@demo.it')->first() ?? User::first();

        if (!$sport || !$allenatore) {
            $this->command->warn('ExerciseEcologicalSeeder: sport pallavolo o allenatore non trovato — skip.');
            return;
        }

        $gesti = GestoTecnico::where('sport_id', $sport->id)->pluck('id', 'nome');

        // fundamental (eng) → gesto_tecnico_id
        $fundamentalMap = [
            'reception' => $gesti['Ricezione'] ?? null,
            'setting'   => $gesti['Palleggio'] ?? ($gesti['Alzata'] ?? null),
            'attack'    => $gesti['Attacco'] ?? null,
            'serve'     => $gesti['Battuta'] ?? null,
            'block'     => $gesti['Muro'] ?? null,
            'team_play' => null,
        ];

        // age_group (eng) → categoria_eta (it)
        $ageMap = [
            'all'    => null,
            'u14'    => 'U14',
            'u16'    => 'U16',
            'u18'    => 'U18',
            'u20'    => 'U20',
            'senior' => 'Senior',
        ];

        // ── Dati esercizi ─────────────────────────────────────────────────────
        // Campi interni (non column names): name, description, fundamental, age_group
        // + tag ecologici 1:1 con le colonne DB.

        $exercises = [

            // =================================================================
            // 1. RICEZIONE / DIFESA (10 esercizi)
            // =================================================================

            [
                'name'                => 'Ricezione monolaterale',
                'description'         => 'Il ricettore usa solo il braccio sinistro o destro per effettuare la ricezione. Il battitore serve normalmente. Alterna il braccio ogni 5 battute. Forza la lettura anticipata della traiettoria e l\'adattamento posturale.',
                'fundamental'         => 'reception',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'space']),
            ],
            [
                'name'                => 'Ricezione su battuta corta/lunga a sorpresa',
                'description'         => 'Il battitore, senza segnale preventivo, serve alternativamente corto (zona 2-3) o lungo (zona 1-5). Il ricettore deve leggere il gesto del battitore e muoversi prima del rimbalzo. Target: palleggiatore in zona 3.',
                'fundamental'         => 'reception',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'space', 'time']),
            ],
            [
                'name'                => 'Ricezione in campo ridotto 3x3',
                'description'         => 'Campo ridotto a 3 metri per lato. Battute normali da metà campo opposto. La riduzione dello spazio aumenta la densità decisionale e riduce i tempi di lettura. Giocano 2 ricettori per lato.',
                'fundamental'         => 'reception',
                'age_group'           => 'all',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'time', 'teammate']),
            ],
            [
                'name'                => 'Ricezione con scelta immediata 1a/2a palla',
                'description'         => 'Dopo la ricezione il palleggiatore chiama "primo" o "secondo": il ricettore deve già essere pronto per attaccare in primo tempo o spostarsi in parallelo. La decisione del palleggiatore arriva dopo la ricezione, non prima.',
                'fundamental'         => 'reception',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'teammate', 'time']),
            ],
            [
                'name'                => 'Difesa su attacco da posizione sconosciuta',
                'description'         => 'Il difensore è girato di spalle. L\'allenatore lancia la palla all\'attaccante che colpisce: al suono di un fischio il difensore si gira e difende. Allena la reattività percettiva e la lettura del gesto atletico dell\'attaccante.',
                'fundamental'         => 'reception',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'opponent', 'time']),
            ],
            [
                'name'                => 'Ricezione float con occhi bendati fino al rimbalzo',
                'description'         => 'Il ricettore indossa una fascia sugli occhi fino al momento in cui la palla supera la rete, poi la toglie e riceve. Allena la concentrazione sull\'informazione visiva al momento critico e riduce il rumore percettivo pre-battuta.',
                'fundamental'         => 'reception',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'time']),
            ],
            [
                'name'                => 'Difesa con rete alta +30cm',
                'description'         => 'La rete viene alzata di 30 cm rispetto all\'altezza standard. Gli attacchi cambiano traiettoria (più piatti o più incrociati): il difensore deve ricalibrare le proprie aspettative sulla direzione della palla. Ottimo per rompere abitudini difensive rigide.',
                'fundamental'         => 'reception',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['net', 'ball', 'space']),
            ],
            [
                'name'                => 'Ricezione K1 con costruzione completa',
                'description'         => 'Battuta reale → ricezione → alzata → attacco → difesa → contrattacco. Il punto si chiude sempre. Il ricettore è consapevole che la ricezione impatta direttamente la qualità dell\'attacco. Alta rappresentatività di gara.',
                'fundamental'         => 'reception',
                'age_group'           => 'senior',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'teammate', 'opponent', 'space']),
            ],
            [
                'name'                => 'Difesa 1vs1 su palla spinta dall\'allenatore',
                'description'         => 'Il difensore fronteggia l\'allenatore a 3 metri. L\'allenatore spinge la palla in direzioni imprevedibili con variazione di ritmo. Il difensore deve mantenere la posizione bassa e rispondere. Semplice ma alta intensità percettiva.',
                'fundamental'         => 'reception',
                'age_group'           => 'u14',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'time', 'space']),
            ],
            [
                'name'                => 'Ricezione con target mobile',
                'description'         => 'Il palleggiatore si muove in zona 2-3-4 senza segnalare dove andrà. Il ricettore deve leggere il movimento del palleggiatore mentre riceve per orientare il bagher nella direzione giusta. Allena la visione periferica e la coordinazione spaziale.',
                'fundamental'         => 'reception',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'teammate', 'space']),
            ],

            // =================================================================
            // 2. PALLEGGIO (10 esercizi)
            // =================================================================

            [
                'name'                => 'Palleggio con informazione ritardata',
                'description'         => 'Il palleggiatore riceve la palla e deve attendere il segnale dell\'allenatore (colore, numero o direzione) per decidere dove alzare. Il segnale arriva 0.5s dopo la ricezione. Allena la capacità di ritardare la decisione e mantenere più opzioni aperte.',
                'fundamental'         => 'setting',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'time', 'ball']),
            ],
            [
                'name'                => 'Palleggio con un attaccante nascosto',
                'description'         => 'Due attaccanti ai lati, uno è dietro il tabellone/schermo e non visibile fino all\'ultimo momento. Il palleggiatore deve comunque distribuire il gioco leggendo chi è disponibile. Allena la gestione dell\'incertezza informativa.',
                'fundamental'         => 'setting',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'opponent', 'space']),
            ],
            [
                'name'                => 'Palleggio in salto senza rincorsa',
                'description'         => 'Il palleggiatore palleggia sempre in salto ma senza passi di rincorsa: parte da fermo. Rimuove il ritmo automatico del movimento, forza la riorganizzazione del timing e della coordinazione mano-palla.',
                'fundamental'         => 'setting',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'time']),
            ],
            [
                'name'                => 'Palleggio con muro simulato variabile',
                'description'         => 'Un giocatore simula il muro con le braccia alzate in zona 4, 2 o centro, cambiando posizione prima dell\'alzata. Il palleggiatore deve leggere la posizione del muro simulato e distribuire di conseguenza.',
                'fundamental'         => 'setting',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'teammate', 'space']),
            ],
            [
                'name'                => 'Palleggio da posizioni non standard',
                'description'         => 'Il palleggiatore riceve palloni da zone diverse del campo (zona 1, zona 6, vicino alla rete, lontano). Deve adattare l\'alzata alla posizione di partenza non standard. Non c\'è una "posizione corretta" preassegnata.',
                'fundamental'         => 'setting',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'space', 'teammate']),
            ],
            [
                'name'                => 'Palleggio 3vs3 con obbligo di variare alzata',
                'description'         => '3vs3. Regola: il palleggiatore non può alzare due volte di seguito nella stessa zona. Obbliga la variazione del gioco e allena la lettura delle difese avversarie per sfruttare zone scoperte.',
                'fundamental'         => 'setting',
                'age_group'           => 'u16',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'opponent', 'space']),
            ],
            [
                'name'                => 'Palleggio con risposta al colore del pannello',
                'description'         => 'Quattro pannelli colorati in zone diverse del campo. L\'allenatore accende un colore nell\'istante in cui il palleggiatore tocca la palla. Il palleggiatore deve alzare verso quel colore. Allena la decisione sotto pressione temporale.',
                'fundamental'         => 'setting',
                'age_group'           => 'senior',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'time', 'teammate']),
            ],
            [
                'name'                => 'Palleggio di bagher fuori rete',
                'description'         => 'Il palleggiatore riceve palle ravvicinate alla rete (entro 50cm) e deve palleggiare indietro con il bagher invece che con le mani. Forza la lettura della distanza dalla rete e la scelta del gesto in base al vincolo spaziale.',
                'fundamental'         => 'setting',
                'age_group'           => 'u14',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['net', 'ball', 'space']),
            ],
            [
                'name'                => 'Palleggio con attaccante che chiama il tempo',
                'description'         => 'È l\'attaccante a chiamare il momento dell\'alzata battendo le mani. Il palleggiatore deve rispettare quel timing. Inverte il controllo del ritmo: non è il palleggiatore a dettare, ma l\'attaccante.',
                'fundamental'         => 'setting',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'time', 'ball']),
            ],
            [
                'name'                => 'Palleggio con due palloni alternati',
                'description'         => 'L\'allenatore lancia palloni alternati da destra e sinistra in rapida sequenza. Il palleggiatore deve alzare ogni pallone verso un target diverso (dx → zona 4, sx → zona 2). Allena l\'orientamento spaziale rapido e la dissociazione destra/sinistra.',
                'fundamental'         => 'setting',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'space', 'time']),
            ],

            // =================================================================
            // 3. ATTACCO (10 esercizi)
            // =================================================================

            [
                'name'                => 'Attacco con muro reale e difesa posizionata',
                'description'         => 'Attacco in situazione reale con muratori veri e difensori posizionati. L\'attaccante deve leggere il muro (braccia, posizione, timing) e scegliere la soluzione: pipe, diagonale, pallonetto, fast. Nessuna zona presegnalata.',
                'fundamental'         => 'attack',
                'age_group'           => 'all',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'net', 'ball']),
            ],
            [
                'name'                => 'Attacco con palla in traiettorie variabili',
                'description'         => 'Il palleggiatore varia intenzionalmente altezza, distanza dalla rete e lateralità dell\'alzata. L\'attaccante non sa in anticipo dove arriverà la palla. Deve adattare la rincorsa e il timing invece di eseguire un gesto fisso.',
                'fundamental'         => 'attack',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'time', 'space']),
            ],
            [
                'name'                => 'Attacco con zone proibite variabili',
                'description'         => 'Sul campo avversario sono segnate con coni 2-3 zone proibite che cambiano ogni 5 attacchi. L\'attaccante deve scegliere la zona libera leggendo la difesa avversaria. Allena la lettura del campo e la scelta tattica in tempo reale.',
                'fundamental'         => 'attack',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'opponent', 'ball']),
            ],
            [
                'name'                => 'Attacco da salto da fermo (no rincorsa)',
                'description'         => 'L\'attaccante parte con i piedi già in posizione di stacco, senza rincorsa. Rimuove il pattern automatico dell\'approccio e forza la riorganizzazione del coordinamento braccio-gamba. Usato per sbloccare schemi motori rigidi.',
                'fundamental'         => 'attack',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'time']),
            ],
            [
                'name'                => 'Attacco con muro che si sposta all\'ultimo',
                'description'         => 'Un muratore parte centrato e si sposta a destra o sinistra nell\'ultimo secondo prima dello stacco dell\'attaccante. L\'attaccante deve leggere il movimento e attaccare dove il muro non c\'è più.',
                'fundamental'         => 'attack',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'net']),
            ],
            [
                'name'                => 'Attacco 2vs2 campo piccolo con punteggio',
                'description'         => '2vs2 su campo 4x4. Ogni squadra ha un attaccante e un palleggiatore. Il punto finisce sempre. La riduzione dello spazio aumenta la densità del muro e forza l\'attaccante a trovare soluzioni creative (tocco, pallonetto, fast).',
                'fundamental'         => 'attack',
                'age_group'           => 'u14',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'opponent', 'teammate', 'net']),
            ],
            [
                'name'                => 'Attacco con informazione sul muro ritardata',
                'description'         => 'L\'attaccante parte nella rincorsa senza sapere se ci sarà muro o no. A metà rincorsa l\'allenatore fischia: fischio = c\'è muro, silenzio = campo libero. L\'attaccante deve adattare la scelta a rincorsa già iniziata.',
                'fundamental'         => 'attack',
                'age_group'           => 'senior',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'ball', 'time']),
            ],
            [
                'name'                => 'Attacco con vincolo braccio non dominante',
                'description'         => 'L\'attaccante colpisce la palla con il braccio non dominante. Destrimani → braccio sinistro. Rimuove la dominanza tecnica consolidata e forza la riorganizzazione percettivo-motoria. Usato come esplorazione, non come tecnica.',
                'fundamental'         => 'attack',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'space']),
            ],
            [
                'name'                => 'Attacco in pipe su ricezione reale',
                'description'         => 'Il centrale parte da zona 6 e attacca in pipe su ricezione reale da battuta. Il palleggiatore decide se alzare in pipe o no in base alla qualità della ricezione. L\'attaccante deve leggere la situazione e adattare la rincorsa.',
                'fundamental'         => 'attack',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'teammate', 'opponent']),
            ],
            [
                'name'                => 'Attacco con difensore che rivela la zona all\'ultimo',
                'description'         => 'Un difensore avversario è nascosto. Nell\'istante dello stacco rivela la propria posizione. L\'attaccante deve attaccare dove il difensore non è. Allena la lettura periferica durante la fase aerea del salto.',
                'fundamental'         => 'attack',
                'age_group'           => 'senior',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'ball']),
            ],

            // =================================================================
            // 4. BATTUTA (10 esercizi)
            // =================================================================

            [
                'name'                => 'Battuta con target mobile',
                'description'         => 'Sul campo avversario un giocatore si sposta lentamente tra le zone. Il battitore deve mirare al giocatore in movimento, non a una zona fissa. Allena l\'adattamento continuo del target e la calibrazione spazio-palla.',
                'fundamental'         => 'serve',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'opponent', 'ball']),
            ],
            [
                'name'                => 'Battuta con schieramento difensivo visibile',
                'description'         => 'Prima di battere, il battitore osserva lo schieramento difensivo avversario (3 ricettori posizionati). Deve identificare la zona scoperta e battere lì. Allena la lettura tattica pre-battuta tipica del gioco reale.',
                'fundamental'         => 'serve',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'ball']),
            ],
            [
                'name'                => 'Battuta jump su segnale ritardato',
                'description'         => 'Il battitore lancia la palla in aria ma aspetta il segnale dell\'allenatore (colore o numero) prima di saltare. Il segnale arriva con ritardo variabile (0.3-0.8s). Rompe il ritmo automatico lancio-salto-colpo.',
                'fundamental'         => 'serve',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'time']),
            ],
            [
                'name'                => 'Battuta float con variazione zona ogni punto',
                'description'         => 'Il battitore deve battere in zone diverse a rotazione (1-5-6-1-5...) senza poter ripetere la stessa zona due volte consecutive. Sequenza comunicata dall\'allenatore prima del turno. Allena la calibrazione della forza per distanze diverse.',
                'fundamental'         => 'serve',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'ball']),
            ],
            [
                'name'                => 'Battuta con ricettore che si posiziona tardi',
                'description'         => 'I ricettori entrano in campo solo dopo che il battitore ha lanciato la palla. Il battitore deve adattare la direzione in corsa basandosi su dove si posizionano i ricettori. Simula le situazioni di rottura dello schieramento in gara.',
                'fundamental'         => 'serve',
                'age_group'           => 'senior',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'time']),
            ],
            [
                'name'                => 'Battuta in gioco reale con conseguenza',
                'description'         => 'La battuta apre una sequenza di gioco completa K1. Se il ricettore riceve bene, la squadra guadagna +1 punto bonus. Se la battuta è ace, +2. Se la ricezione è perfetta nonostante la battuta difficile, +1 alla squadra che riceve. Alta rappresentatività.',
                'fundamental'         => 'serve',
                'age_group'           => 'all',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'ball', 'teammate']),
            ],
            [
                'name'                => 'Battuta con un solo arto',
                'description'         => 'Battuta float tenendo il braccio non dominante dietro la schiena. Forza la ristrutturazione dell\'equilibrio e del coordinamento durante il gesto. Esercizio di esplorazione motoria, non di tecnica standard.',
                'fundamental'         => 'serve',
                'age_group'           => 'u14',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball']),
            ],
            [
                'name'                => 'Battuta in pressione temporale',
                'description'         => 'Il battitore ha 5 secondi (segnalati da conto alla rovescia vocale) per completare il gesto dopo il fischio. Simula la pressione temporale reale di gara e il disturbo cognitivo del pubblico/arbitro. Riduce l\'overthinking tecnico.',
                'fundamental'         => 'serve',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['time', 'ball', 'space']),
            ],
            [
                'name'                => 'Battuta a coppie con confronto diretto',
                'description'         => 'Due battitori si sfidano a turno: devono battere nella zona specificata dall\'allenatore. Chi manca la zona prima di 10 tentativi perde. Introduce pressione competitiva e attenzione alla precisione senza drill meccanico.',
                'fundamental'         => 'serve',
                'age_group'           => 'u14',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'neutral',
                'affordance_targets'  => json_encode(['space', 'ball']),
            ],
            [
                'name'                => 'Battuta ace o out: zona stretta',
                'description'         => 'Si posiziona un nastro a terra che delimita una striscia di 1 metro in zona 1 o 5. Il battitore deve atterrare la palla dentro quella striscia. O è dentro (ace o difficoltà), o è fuori. Nessuna zona di conforto ampia.',
                'fundamental'         => 'serve',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'neutral',
                'affordance_targets'  => json_encode(['space', 'ball']),
            ],

            // =================================================================
            // 5. MURO (10 esercizi)
            // =================================================================

            [
                'name'                => 'Muro su attacco con rincorsa variabile',
                'description'         => 'L\'attaccante cambia la rincorsa (da 3, da 2, da 1 passo) senza preavviso. Il muratore deve leggere la rincorsa e adattare il timing di salto invece di usare un ritmo fisso. Allena la lettura del gesto atletico avversario.',
                'fundamental'         => 'block',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'time', 'net']),
            ],
            [
                'name'                => 'Muro 1vs1 su pipe',
                'description'         => 'Un centrale difende da solo contro attacchi in pipe da zona 6. Deve leggere la rincorsa del centrale avversario, decidere se murarla o arretrare in difesa. Allena la scelta muro/difesa in condizioni reali.',
                'fundamental'         => 'block',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'net']),
            ],
            [
                'name'                => 'Muro con copertura obbligatoria',
                'description'         => 'Dopo ogni muro il muratore deve immediatamente coprire la zona retromuro (zona 6). Un secondo attaccante riceve la palla rimbalzata e riattacca. Il muratore deve murarla di nuovo o difenderla. Allena la transizione muro-difesa.',
                'fundamental'         => 'block',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'teammate']),
            ],
            [
                'name'                => 'Muro doppio con comunicazione',
                'description'         => 'Due muratori in zona 3-4. Solo uno dei due deve saltare: devono comunicare vocalmente ("mio!" / "tuo!") nell\'istante dello stacco. L\'allenatore non assegna zone. Allena la comunicazione e la lettura condivisa.',
                'fundamental'         => 'block',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'opponent', 'net']),
            ],
            [
                'name'                => 'Muro su alzata sconosciuta',
                'description'         => 'Il palleggiatore avversario non rivela la zona di alzata: può alzare in 2, 4 o pipe. Il muratore deve leggere le spalle e le mani del palleggiatore per anticipare la direzione. Nessuna assegnazione di zona preventiva.',
                'fundamental'         => 'block',
                'age_group'           => 'senior',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'net', 'time']),
            ],
            [
                'name'                => 'Muro con salto da posizione scomoda',
                'description'         => 'Il muratore parte inginocchiato o seduto. Al fischio si alza e salta per murare. Rompe il pattern posturale pre-salto e allena la riorganizzazione rapida del corpo verso la rete.',
                'fundamental'         => 'block',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['net', 'ball', 'time']),
            ],
            [
                'name'                => 'Muro 3vs3 con punteggio solo da muro diretto',
                'description'         => '3vs3. I punti si segnano solo con muro diretto (palla a terra dopo il muro senza toccare difensori). Gli attacchi valgono 0. Crea un contesto in cui il muro è l\'obiettivo primario, aumentando la motivazione alla lettura dell\'attacco.',
                'fundamental'         => 'block',
                'age_group'           => 'u18',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'net', 'space']),
            ],
            [
                'name'                => 'Muro su attacco da posizione arretrata',
                'description'         => 'L\'attaccante colpisce da zona 6 (attacco da seconda linea). Il muratore deve adattare la posizione alla rete e il timing perché la traiettoria è più piatta e meno prevedibile rispetto all\'attacco da zona 4.',
                'fundamental'         => 'block',
                'age_group'           => 'senior',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'ball', 'net']),
            ],
            [
                'name'                => 'Muro con disturbo laterale',
                'description'         => 'Un secondo giocatore tocca il gomito del muratore nell\'istante dello stacco. Il disturbo fisico (leggero e sicuro) allena il mantenimento della concentrazione e dell\'orientamento spaziale in condizioni di disturbo sensoriale.',
                'fundamental'         => 'block',
                'age_group'           => 'u16',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'organism',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['net', 'ball', 'time']),
            ],
            [
                'name'                => 'Muro con scelta: chiudi o apri',
                'description'         => 'L\'allenatore assegna prima del rally se il muratore deve "chiudere" (coprire la diagonale) o "aprire" (coprire il lungolinea). L\'assegnazione cambia ogni punto. Allena la consapevolezza tattica della scelta di copertura.',
                'fundamental'         => 'block',
                'age_group'           => 'u18',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['opponent', 'space', 'net']),
            ],

            // =================================================================
            // 6. GIOCO DI SQUADRA / SISTEMI (10 esercizi)
            // =================================================================

            [
                'name'                => '6vs6 con due palloni in gioco',
                'description'         => 'Si gioca con due palloni simultaneamente. Quando uno esce, entra immediatamente dall\'altra parte. I giocatori devono gestire l\'attenzione divisa, comunicare rapidamente e adattarsi al ritmo caotico. Allena la consapevolezza spaziale collettiva.',
                'fundamental'         => 'team_play',
                'age_group'           => 'senior',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'space', 'time', 'ball']),
            ],
            [
                'name'                => '4vs4 con campo asimmetrico',
                'description'         => 'Un lato del campo è largo 7m, l\'altro è largo 4m. Le squadre cambiano lato ogni 5 punti. La forma del campo crea affordance diverse (attacchi in diagonale sul lato largo, gioco stretto sul lato piccolo). Allena l\'adattamento tattico strutturale.',
                'fundamental'         => 'team_play',
                'age_group'           => 'all',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'teammate', 'opponent']),
            ],
            [
                'name'                => '6vs6 con obbligo di tocco per tutti',
                'description'         => 'Regola: il punto è valido solo se almeno 4 giocatori su 6 hanno toccato la palla nel rally. Obbliga la costruzione collettiva del gioco, elimina i solisti e aumenta la consapevolezza del movimento senza palla.',
                'fundamental'         => 'team_play',
                'age_group'           => 'u16',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'space', 'ball']),
            ],
            [
                'name'                => 'Transizione K1-K2 continua',
                'description'         => 'Battuta → ricezione → costruzione → attacco (K1). La difesa riprende la palla e costruisce subito il contrattacco (K2). Il punto finisce solo a terra. Non si interrompe mai tra K1 e K2. Alta rappresentatività del gioco reale.',
                'fundamental'         => 'team_play',
                'age_group'           => 'all',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'none',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'teammate', 'opponent', 'space']),
            ],
            [
                'name'                => '3vs3 con palleggiatore a rotazione',
                'description'         => '3vs3. Non c\'è un palleggiatore fisso: il secondo tocco deve essere fatto dal giocatore più vicino alla palla. Nessuna specializzazione. Allena la decisione collettiva senza ruoli prestabiliti.',
                'fundamental'         => 'team_play',
                'age_group'           => 'u14',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'ball', 'space']),
            ],
            [
                'name'                => '6vs6 con punteggio differenziato per zona d\'attacco',
                'description'         => 'Attacco da zona 4 = 1pt. Attacco da zona 2 = 1pt. Attacco in pipe = 2pt. Fast al centro = 2pt. Crea un sistema di affordance che incentiva la variazione del gioco senza imporre tattiche specifiche.',
                'fundamental'         => 'team_play',
                'age_group'           => 'u18',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'teammate', 'opponent']),
            ],
            [
                'name'                => 'Gioco con sistema difensivo scelto in campo',
                'description'         => 'Prima di ogni battuta avversaria, il capitano (o libero) chiama il sistema difensivo tra due opzioni disponibili (es. "rientro 6" o "libero avanzato"). La squadra deve adattarsi in tempo reale alla scelta. L\'allenatore non interviene.',
                'fundamental'         => 'team_play',
                'age_group'           => 'senior',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'task',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'opponent', 'space']),
            ],
            [
                'name'                => '5vs6 (squadra in svantaggio numerico)',
                'description'         => 'Una squadra gioca con 5 giocatori contro 6. La squadra da 5 deve riorganizzarsi autonomamente per coprire il campo. Allena la comunicazione, la copertura degli spazi e il problem-solving tattico collettivo sotto pressione.',
                'fundamental'         => 'team_play',
                'age_group'           => 'u18',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'medium',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['space', 'teammate', 'opponent']),
            ],
            [
                'name'                => 'Free ball con ricostruzione sotto pressione',
                'description'         => 'L\'allenatore lancia una free ball. La squadra costruisce il contrattacco. Immediatamente dopo l\'attacco, l\'allenatore lancia una seconda free ball. La squadra deve riorganizzarsi senza pausa. Simula la pressione di gara nel terzo set.',
                'fundamental'         => 'team_play',
                'age_group'           => 'all',
                'exercise_category'   => 'situational',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'high',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['ball', 'teammate', 'space', 'time']),
            ],
            [
                'name'                => '6vs6 con cambio di schema a metà rally',
                'description'         => 'L\'allenatore fischia a metà rally: le squadre devono scambiare un giocatore tra loro (quello più vicino alla rete va dall\'altra parte). Il gioco continua immediatamente. Allena la fluidità dei ruoli e la consapevolezza collettiva estrema.',
                'fundamental'         => 'team_play',
                'age_group'           => 'senior',
                'exercise_category'   => 'game_form',
                'paradigm_primary'    => 'ecological',
                'constraint_type'     => 'environment',
                'representativeness'  => 'low',
                'feedback_suggestion' => 'interrogative_perceptual',
                'affordance_targets'  => json_encode(['teammate', 'space', 'ball']),
            ],

        ];

        // ── Inserimento idempotente ───────────────────────────────────────────
        $inserted = 0;
        $updated  = 0;

        foreach ($exercises as $e) {
            $gestoId   = $fundamentalMap[$e['fundamental']] ?? null;
            $categoriaEta = $ageMap[$e['age_group']] ?? null;

            $esercizio = Esercizio::firstOrCreate(
                ['nome' => $e['name'], 'sport_id' => $sport->id],
                [
                    'sport_id'            => $sport->id,
                    'creato_da'           => $allenatore->id,
                    'gesto_tecnico_id'    => $gestoId,
                    'fase'                => 'potenziamento',
                    'metodologia'         => 'globale',
                    'durata_min'          => 15,
                    'n_salti'             => 0,
                    'n_gesti'             => 0,
                    'is_pubblico'         => true,
                    'categoria_eta'       => $categoriaEta,
                    'descrizione'         => $e['description'],
                    'exercise_category'   => $e['exercise_category'],
                    'paradigm_primary'    => $e['paradigm_primary'],
                    'constraint_type'     => $e['constraint_type'],
                    'representativeness'  => $e['representativeness'],
                    'feedback_suggestion' => $e['feedback_suggestion'],
                    'affordance_targets'  => $e['affordance_targets'],
                ]
            );

            if ($esercizio->wasRecentlyCreated) {
                $inserted++;
            } else {
                // Aggiorna tag ecologici e descrizione (idempotente)
                $esercizio->update([
                    'is_pubblico'         => true,
                    'categoria_eta'       => $categoriaEta,
                    'descrizione'         => $e['description'],
                    'exercise_category'   => $e['exercise_category'],
                    'paradigm_primary'    => $e['paradigm_primary'],
                    'constraint_type'     => $e['constraint_type'],
                    'representativeness'  => $e['representativeness'],
                    'feedback_suggestion' => $e['feedback_suggestion'],
                    'affordance_targets'  => $e['affordance_targets'],
                ]);
                $updated++;
            }

            $esercizio->syncRuoli([]);
        }

        $this->command->info("✅ ExerciseEcologicalSeeder: {$inserted} inseriti, {$updated} aggiornati (tot. 60 esercizi ecologici).");
        $this->command->info('   Fondamentali: ricezione/difesa (10), palleggio (10), attacco (10), battuta (10), muro (10), gioco di squadra (10).');
    }
}
